#!/bin/bash

TESTFILE=/tmp/anste-openvpn-ready-$$

openvpn --config foobar-server-client.conf --daemon --route-up "touch $TESTFILE" --log /tmp/$TESTFILE.log

for i in `seq 1 20`
do
    if [ -f $TESTFILE ]
    then
        echo "OpenVPN connected"
        break
    else
        sleep 1
    fi
done

cat /tmp/$TESTFILE.log

rm $TESTFILE $TESTFILE.log

echo "Expecting foo on internal:1100"
nc -w 5 internal 1100 | grep foo 
