#!/bin/sh

export http_proxy="192.168.2.1:3128"

echo "HTTP request to www.lupaland.com"
wget -r -t 3 www.lupaland.com -O output.html

echo "Checking if access was denied"
grep "Access has been Denied" output.html 
