#!/bin/sh

export http_proxy="192.168.2.1:3128"

for i in `seq 1 10`
do
    wget -r -t 3 www.google.com

    if [ $? ]
    then
        echo "Access allowed."
        exit 0
    else
        sleep 1
    fi
done    

echo "Test failed (timeout)."
exit 1
