#!/usr/bin/perl

# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use ANSTE::Scenario::Image;
use ANSTE::System::BaseScriptGen;

use constant IMAGE => "data/images/sarge-ebox-base.xml";

my $image = new ANSTE::Scenario::Image;
$image->loadFromFile(IMAGE);
my $gen = new ANSTE::System::BaseScriptGen($image);
open(my $file, ">", "test.sh");
$gen->writeScript($file);
close($file);
