#!/usr/bin/perl

# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use ANSTE::Deploy::Image;
use ANSTE::System::HostInstallGen;

use constant HOSTNAME => 'hostname1';
use constant IP => '192.168.45.192';

my $image = new ANSTE::Deploy::Image(name => HOSTNAME,
                                     ip => IP);

my $gen = new ANSTE::System::HostInstallGen($image);
my $file = \*STDOUT;
$gen->writeScript($file);
