#!/usr/bin/perl

# Copyright (C) 2007-2011 José Antonio Calvo Fernández <jacalvo@zentyal.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use ANSTE::Image::Image;
use ANSTE::ScriptGen::HostPreInstall;
use ANSTE::Scenario::Scenario;

use constant SCENARIO => 'big.xml';

my $arg = $ARGV[0] ? $ARGV[0] : SCENARIO;

my $scenario = new ANSTE::Scenario::Scenario;
$scenario->loadFromFile($arg);
my $hosts = $scenario->hosts();

use constant IP => '192.168.45.192';

foreach my $host (@{$hosts}) {
    my $name = $host->name();
    print "------ BEGIN host $name ------\n";

    my $image = new ANSTE::Image::Image(name => $name,
                                        ip => IP);
    $image->setNetwork($host->network());                                        

    my $gen = new ANSTE::ScriptGen::HostPreInstall($image);
    my $file = \*STDOUT;
    $gen->writeScript($file);
    print "------ END host $name ------\n\n";
}    
