#!/usr/bin/perl

# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use Scenario::Scenario;
use System::SetupScriptGen;

use constant SCENARIO => "data/scenario.xml";

my $scenario = new Scenario::Scenario;
$scenario->loadFromFile(SCENARIO);
my @servers = $scenario->servers();
my $gen = new System::SetupScriptGen($servers[0], $scenario->system());
open(my $file, ">", "test.sh");
$gen->writeScript($file);
close($file);
