#!/usr/bin/perl

# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use ANSTE::Comm::SlaveClient;

use constant HOST => 'localhost';
use constant PORT => 8001;

my $DEBUG;

my $command = $ARGV[0];

sub usage
{
    print "Usage: anste-slave ready | finished <return value>\n";
}

if (@ARGV < 1) {
    usage();
    exit(1);
}

if ($command eq 'ready') {
    handleReady();
}
elsif ($command eq 'finished') {
    if (@ARGV < 2) {
        usage();
        exit(1);
    }
    handleFinished();
}
else { 
    usage();
    exit(1);
}

sub handleReady
{
    my $client = getClient();
    my $ok = $client->hostReady();
    exit(!$ok);
}

sub handleFinished
{
    open($DEBUG, '>', '/tmp/SLAVE_DEBUG');
    print $DEBUG "handleFinished\n";
    my $client = getClient();
    print $DEBUG "before getClient\n";
    my $ret = $ARGV[1];
    my $ok = $client->executionFinished($ret);
    print $DEBUG "before executionFinished\n";
    exit(!$ok);
}

sub getClient 
{
    # Create and return the client object
    my $URL = "http://".HOST.":8001";
    my $client = new ANSTE::Comm::SlaveClient;
    print $DEBUG "before the new SlaveClient\n" if $DEBUG;
    $client->connect($URL);
    print $DEBUG "connected\n" if $DEBUG;
    return $client;
}
