#!/usr/bin/perl

# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use ANSTE::Report::Report;
use ANSTE::Report::SuiteResult;
use ANSTE::Report::TestResult;
use ANSTE::Report::TextWriter;


my $report = new ANSTE::Report::Report();

my $suite = new ANSTE::Report::SuiteResult();
$suite->setName('Suite 1');
my $test = new ANSTE::Report::TestResult();
$test->setName('Test 1');
$test->setValue(1);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 2');
$test->setValue(0);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 3');
$test->setValue(0);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 4');
$test->setValue(1);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 5');
$test->setValue(0);
$suite->add($test);
$report->add($suite);

$suite = new ANSTE::Report::SuiteResult();
$suite->setName('Suite 2');
$test = new ANSTE::Report::TestResult();
$test->setName('Test 1');
$test->setValue(0);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 2');
$test->setValue(0);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 3');
$test->setValue(1);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 4');
$test->setValue(1);
$suite->add($test);
$test = new ANSTE::Report::TestResult();
$test->setName('Test 5');
$test->setValue(1);
$suite->add($test);

$report->add($suite);
my $writer = new ANSTE::Report::TextWriter($report);
$writer->write(\*STDOUT);
