#!/usr/bin/perl

# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use ANSTE::Report::Report;
use ANSTE::Report::SuiteResult;
use ANSTE::Report::TestResult;
use ANSTE::Report::TextWriter;

my $report = new ANSTE::Report::Report();

my $suite = new ANSTE::Report::SuiteResult();
my $s = new ANSTE::Test::Suite();
$s->setName('Suite 1');
$s->setDesc('Here goes the suite description');
$suite->setSuite($s);

my $test = new ANSTE::Report::TestResult();
my $t = new ANSTE::Test::Test();
$t->setName('Test 2');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(1);
$suite->add($test);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 3');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(0);
$suite->add($test);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 4');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(1);
$suite->add($test);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 5');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(0);
$suite->add($test);

$report->add($suite);

$suite = new ANSTE::Report::SuiteResult();
$s = new ANSTE::Test::Suite();
$s->setName('Suite 2');
$s->setDesc('Here goes the suite description');
$suite->setSuite($s);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 2');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(0);
$suite->add($test);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 3');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(0);
$suite->add($test);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 4');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(0);
$suite->add($test);

$test = new ANSTE::Report::TestResult();
$t = new ANSTE::Test::Test();
$t->setName('Test 5');
$t->setDesc('Here goes the test description');
$test->setTest($t);
$test->setValue(1);
$suite->add($test);

$report->add($suite);

my $writer = new ANSTE::Report::TextWriter($report);
$writer->write(\*STDOUT);
