# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package ANSTE::System::BaseScriptGen;

use strict;
use warnings;

use ANSTE::Scenario::BaseImage;
use ANSTE::Config;

sub new # (image) returns new BaseScriptGen object
{
	my ($class, $image) = @_;

	my $self = {};
	
	$self->{image} = $image;
    my $system = ANSTE::Config->instance()->system();

    eval("use ANSTE::System::$system");
    die "Can't load package $system: $@" if $@;

    $self->{system} = "ANSTE::System::$system"->new();

	bless($self, $class);

	return $self;
}

sub writeScript # (file)
{
	my ($self, $file) = @_;

	print $file "#!/bin/sh\n";
	my $image = $self->{image}->name();
	print $file "\n# Configuration file for image $image\n";
	print $file "# Generated by ANSTE\n\n"; 
    $self->_writePreInstall($file);
	$self->_writePackageInstall($file);
    $self->_writePostInstall($file);
    $self->_writeFirewallRules($file);
}

sub _writePreInstall # (file)
{
    my ($self, $file) = @_;

    my $system = $self->{system};

    my $vars = $system->installVars();
    print $file $vars;

    my $command = $system->updatePackagesCommand();
    print $file "$command\n\n";
}

sub _writePackageInstall # (file)
{
	my ($self, $file) = @_;

    my $system = $self->{system};

	my @packages = @{$self->{image}->packages()->list()};

	print $file "# Install packages\n";
    my $command = $system->installPackagesCommand(@packages); 
	print $file "$command\n\n";
}

sub _writePostInstall # (file)
{
    my ($self, $file) = @_;

    my $system = $self->{system};

    my $command = $system->cleanPackagesCommand();

    print $file "$command\n\n";
}

sub _writeFirewallRules # (file)
{
    my ($self, $file) = @_;

    my $system = $self->{system};

    my $rules = $system->firewallDefaultRules();

    print $file "# Set firewall configuration\n";
    print $file "$rules\n"
}

1;
