# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package ANSTE::System::CommInstallGen;

use strict;
use warnings;

use ANSTE::Scenario::Host;

# Generates the scripts that installs ansted and anste-slave
# in a base image.

sub new # (image) returns new CommInstallGen object
{
	my ($class, $image) = @_;

	my $self = {};

    $self->{image} = $image;
	
	bless($self, $class);

	return $self;
}

sub writeScript # (file)
{
	my ($self, $file) = @_;

	print $file "#!/bin/sh\n";
	my $host = $self->{image}->name();
	print $file "\n# Installation script for ansted and anste-slave\n";
	print $file "# Generated by ANSTE for host $host\n\n"; 

    print $file "# TODO: Check arguments\n\n";

    print $file "# Receives the mount point of the image as an argument\n";
    print $file "MOUNT='".'$1'."'\n\n";

    my $masterIP = '192.168.45.111'; # FIXME: Get it well

    print $file "MASTER_IP='$masterIP'\n\n";

    $self->_writeCopyFiles($file);

    $self->_writeHosts($file);

    print "# Stores the master's IP so anste-slave can read it\n";
    print $file 'echo $MASTER_IP > $MOUNT/var/local/anste.master'."\n";
}

sub _writeCopyFiles # (file)
{
    my ($self, $file) = @_;

    print $file "# Copy necessary files\n";
    my $commPath = '/usr/local/lib/site_perl/ANSTE/Comm/';
    print $file 'mkdir -p $MOUNT'."$commPath\n";

    my %fileDest = ('bin/ansted' => '/usr/local/bin/',
                    'bin/anste-slave' => '/usr/local/bin',
                    'lib/ANSTE/Comm/*.pm' => $commPath,
                    'data/conf/ansted' => '/etc/init.d/');                 
    
    foreach my $orig (keys %fileDest) {
        print $file "cp $orig ".'$MOUNT'."$fileDest{$orig}\n";
    }
    print $file "\n";
}

sub _writeHosts # (file)
{
    my ($self, $file) = @_;

    my $host = $self->{image}->name();

    print $file "# Write /etc/hosts\n";
    print $file 'cat << EOF > $MOUNT/etc/hosts'."\n";
    print $file "127.0.0.1 localhost.localdomain localhost\n";
    print $file "127.0.1.1 $host.localdomain $host\n";
    print $file "\n";
    print $file "# The following lines are desirable for IPv6 capable hosts\n";
    print $file "::1     ip6-localhost ip6-loopback\n";
    print $file "fe00::0 ip6-localnet\n";
    print $file "ff00::0 ip6-mcastprefix\n";
    print $file "ff02::1 ip6-allnodes\n";
    print $file "ff02::2 ip6-allrouters\n";
    print $file "ff02::3 ip6-allhosts\n";
    print $file "EOF\n\n";
}

1;
