# Copyright (C) 2007 José Antonio Calvo Fernández <jacalvo@warp.es> 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package ANSTE::System::SetupScriptGen;

use strict;
use warnings;

use ANSTE::Scenario::Host;
use ANSTE::Config;

sub new # (host) returns new ServerScriptGen object
{
	my ($class, $host) = @_;

	my $self = {};
	
	$self->{host} = $host;
    my $system = ANSTE::Config->instance()->system();

    eval("use ANSTE::System::$system");
    die "Can't load package $system: $@" if $@;

    $self->{system} = "ANSTE::System::$system"->new();

	bless($self, $class);

	return $self;
}

sub writeScript # (file)
{
	my $self = shift;
	my $file = shift;
	print $file "#!/bin/sh\n";
	my $name = $self->{host}->name();
	my $desc = $self->{host}->desc();
	print $file "\n# Configuration file for host $name\n";
	print $file "# Server description: $desc\n";
	print $file "# Generated by ANSTE\n\n"; 
	$self->_writePackageInstall($file);
	$self->_writeNetworkConfig($file);
}

sub _writePackageInstall # (file)
{
	my ($self, $file) = @_;

    my $system = $self->{system};
    
	print $file "# Install packages\n";
	my @packages = @{$self->{host}->packages()->list()};
    my $command = $system->installPackagesCommand(@packages);
	print $file "$command\n\n";
}

sub _writeNetworkConfig # (file)
{
	my ($self, $file) = @_;

    my $system = $self->{system};
	my $network = $self->{host}->network();

    my $config = $system->networkConfig($network);

	print $file "# Write network configuration\n";
    print $file "$config\n\n";
}

1;
