#!/bin/sh
# Start/stop the Advanced Network Service Testing Environment daemon.

function notify_ready
{
    # Wait for network ready
    for i in `seq 1 20`
    do
        HOST=`cat /var/local/anste.master | cut -f1 -d:`
        PORT=`cat /var/local/anste.master | cut -f2 -d:`
        hping2 -c 1 -p $PORT $HOST &> /dev/null
        if [ $? ]
        then
            break 
        else
            sleep 1
        fi
    done        
    # Try to notify
    for i in `seq 1 5`
    do
        /usr/local/bin/anste-slave ready
        if [ $? ]
        then
            break
        else
            sleep 1
            echo -n "Retrying notification to ANSTE master" 
        fi
    done
}

if [ ! -x /usr/local/bin/ansted ]
then
    echo "ANSTEd not installed"
    exit 0
fi

case "$1" in
start)	echo -n "Starting ANSTE daemon"
        start-stop-daemon --start --quiet --pidfile /var/run/ansted.pid --name ansted --startas /usr/local/bin/ansted
        echo "." 
        echo -n "Notifying readiness to ANSTE master"
        notify_ready
        echo "."
	;;
stop)   echo -n "Stopping ANSTE daemon"	
        start-stop-daemon --stop --quiet --pidfile /var/run/ansted.pid --name ansted 
        echo "." 
        ;;
restart) echo -n "Restarting ANSTE daemon" 
        start-stop-daemon --stop --retry 5 --quiet --pidfile /var/run/ansted.pid --name ansted 
        start-stop-daemon --start --quiet --pidfile /var/run/ansted.pid --name ansted --startas /usr/local/bin/ansted
        echo "." 
        ;;
*)	    echo "Usage: /etc/init.d/ansted {start|stop|restart}"
        exit 1 
        ;;
esac
exit 0
