#!/bin/sh
# Start/stop the Advanced Network Service Testing Environment daemon.


if [ ! -x /usr/local/bin/ansted ]
then
    echo "ANSTEd not installed"
    exit 0
fi

case "$1" in
start)	echo -n "Starting ANSTE daemon"
        start-stop-daemon --start --quiet --pidfile /var/run/ansted.pid --name ansted --startas /usr/local/bin/ansted
        echo "." 
        echo -n "Notifying readiness to ANSTE master"
        /usr/local/bin/anste-slave ready
        echo "."
	;;
stop)   echo -n "Stopping ANSTE daemon"	
        start-stop-daemon --stop --quiet --pidfile /var/run/ansted.pid --name ansted 
        echo "." 
        ;;
restart) echo -n "Restarting ANSTE daemon" 
        start-stop-daemon --stop --retry 5 --quiet --pidfile /var/run/ansted.pid --name ansted 
        start-stop-daemon --start --quiet --pidfile /var/run/ansted.pid --name ansted --startas /usr/local/bin/ansted
        echo "." 
        ;;
*)	    echo "Usage: /etc/init.d/ansted {start|stop|restart}"
        exit 1 
        ;;
esac
exit 0
