#!/bin/sh

export http_proxy="192.168.2.1:3128"

for i in `seq 1 10`
do
    echo "HTTP request to www.lupaland.com"
    wget -r -t 3 www.lupaland.com -O output.html

    echo "Checking if access was denied"
    grep "Access has been Denied" output.html 

    if [ $? ]
    then
        echo "Access allowed."
        exit 0
    else
        sleep 1
    fi
done    

echo "Test failed (timeout)."
exit 1
