#!/usr/bin/perl

use Mail::IMAPClient;
use IO::Socket::SSL;

$imap = new Mail::IMAPClient( User => 'eboxtest@foobar',
                              Password => 'eboxtest',
                              Socket => IO::Socket::SSL->new
                              ( Proto => 'tcp',
                                PeerAddr => '192.168.2.1',
                                PeerPort => 993
                              ));

if (not $imap) {
	print "Authentication failed\n";
	exit 1;
} else {
	print "Authentication OK\n";
}

exit 0;
