#!/bin/bash

LOG=/tmp/smbclient-test-$$.log

[ -f test.bin ] && rm test.bin

echo "Trying to get test.bin"
echo "get test.bin" | lftp 192.168.2.1 -u $USER,$PASS > $LOG 2>&1

cat $LOG

echo "Checking for error $ERROR:"
grep $ERROR $LOG

if [ $? != 0 -a -f test.bin ] 
then
    echo "Test ok."
    exit 0
else
    echo "Failed."
    exit 1
fi
