#!/usr/bin/perl

use Net::SMTP;
use Net::SMTP::SSL;

my $smtp;

if ($ENV{SSL}) {
    $smtp = new Net::SMTP::SSL($ENV{SERVER}, Port => 465);
}
else {
    $smtp = new Net::SMTP($ENV{SERVER});
}

if ($ENV{AUTH}) {
    $smtp->auth('eboxtest@foobar', 'eboxtest');
}

$smtp->mail('eboxtest@foobar');
$smtp->to('eboxtest@foobar');

$smtp->data();
$smtp->datasend("To: eboxtest@foobar");
$smtp->datasend("\n");
$smtp->datasend("foo\n");
$smtp->dataend();

$smtp->quit();
