#!/usr/bin/perl

use Net::SMTP;
use Net::SMTP::SSL;

my $smtp;

my $TO = $ENV{TO};

if ($ENV{SSL}) {
    $smtp = new Net::SMTP::SSL($ENV{SERVER}, Port => 465);
}
else {
    $smtp = new Net::SMTP($ENV{SERVER});
}

if ($ENV{AUTH}) {
    $smtp->auth('eboxtest@foobar', 'eboxtest');
}

$smtp->mail('eboxtest@foobar');
$smtp->to($TO);

$smtp->data();
$smtp->datasend("To: $TO");
$smtp->datasend("\n");
$smtp->datasend("que barbaro\n");
$smtp->dataend();

$smtp->quit();
