#!/bin/sh

IFACE=eth1

PPP_USER=ppp_user
PPP_PASS=ppp_pass

echo "$PPP_USER * $PPP_PASS" >> /etc/ppp/chap-secrets

cat <<EOF > /etc/ppp/peers/anste-dsl-provider
user $PPP_USER
noipdefault
usepeerdns
defaultroute
hide-password
lcp-echo-interval 20
lcp-echo-failure 3
connect /bin/true
noauth
persist
mtu 1492
noaccomp
default-asyncmap
plugin rp-pppoe.so $IFACE
EOF

ifconfig $IFACE up

# Delete default anste route if it exists
route del default gw 10.6.7.1

pon anste-dsl-provider

for i in `seq 1 10`
do
    plog
    if plog | grep -i 'address'
    then
        echo "Connected!!"
        exit 0
    fi
    sleep 1
done

echo "Timeout"
exit 1

