#!/bin/bash

SCRIPT=/var/local/anste/generate-bundle 

echo "Trying to generate bundle..."

BUNDLE=`perl $SCRIPT foobar-server $CLIENT $ROUTER`

echo "Bundle generated at $BUNDLE"

echo "Moving to /var/www ..."
mv $BUNDLE /var/www/ || echo "Error"


echo "Giving read permission"
chmod +r "/var/www/`basename $BUNDLE`" || echo "Error"

test -r "/var/www/`basename $BUNDLE`"
