# Copyright (C) 2007-2011 José Antonio Calvo Fernández <jacalvo@zentyal.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package ANSTE::ScriptGen::BasePreInstall;

use strict;
use warnings;

use ANSTE::Scenario::BaseImage;
use ANSTE::Config;
use ANSTE::Exceptions::MissingArgument;
use ANSTE::Exceptions::InvalidType;
use ANSTE::Exceptions::InvalidFile;

# Class: BasePreInstall
#
#   Writes the setup script for a base image that is executed
#   on a mounted image, before creating the virtual machine.
#   The generated script installs ansted and anste-slave in
#   the base image.
#

# Constructor: new
#
#   Constructor for BasePreInstall class.
#
# Parameters:
#
#   image - <ANSTE::Scenario::BaseImage> object.
#
# Returns:
#
#   A recently created <ANSTE::ScriptGen::BasePreInstall> object.
#
# Exceptions:
#
#   <ANSTE::Exceptions::MissingArgument> - throw if argument is not present
#   <ANSTE::Exceptions::InvalidType> - throw if argument has wrong type
#
sub new # (image) returns new CommInstallGen object
{
	my ($class, $image) = @_;
	my $self = {};

    defined $image or
        throw ANSTE::Exceptions::MissingArgument('image');

    if (not $image->isa('ANSTE::Scenario::BaseImage')) {
        throw ANSTE::Exceptions::InvalidType('image',
                                            'ANSTE::Scenario::BaseImage');
    }

    $self->{image} = $image;
    my $system = ANSTE::Config->instance()->system();

    eval "use ANSTE::System::$system";
    die "Can't load package $system: $@" if $@;

    $self->{system} = "ANSTE::System::$system"->new();

	bless($self, $class);

	return $self;
}

# Method: writeScript
#
#   Writes the script to the given file.
#
# Parameters:
#
#   file - String with the name of the file to be written.
#
# Exceptions:
#
#   <ANSTE::Exceptions::MissingArgument> - throw if argument is not present
#   <ANSTE::Exceptions::InvalidFile> - throw if argument is not a writable file
#
sub writeScript # (file)
{
	my ($self, $file) = @_;

    defined $file or
        throw ANSTE::Exceptions::MissingArgument('file');

    if (not -w $file) {
        throw ANSTE::Exceptions::InvalidFile('file', $file);
    }

    my $system = $self->{system};

	print $file "#!/bin/sh\n";
	my $host = $self->{image}->name();
	print $file "\n# Installation script for ansted and anste-slave\n";
	print $file "# Generated by ANSTE for host $host\n\n";

    print $file "# Receives the mount point of the image as an argument\n";
    print $file 'MOUNT=$1'."\n\n";

    $self->_writeCopyFiles($file);
    $self->_writeHostsConfig($file);

    my $config = ANSTE::Config->instance();
    my $port = $config->masterPort();
    # TODO: Not sure if this is correct
    my $masterIP = $config->gateway();
    my $MASTER = "$masterIP:$port";

    print $file "# Stores the master address so anste-slave can read it\n";
    my $command = $system->storeMasterAddress($MASTER);
    print $file "$command\n";

    # To allow passwordless logins with anste-connect
    print $file "sed -i 's/(ALL) ALL/(ALL) NOPASSWD:ALL/g' \$MOUNT/etc/sudoers\n"
    print $file "echo 'sudo su -' >> \$MOUNT/home/ubuntu/.bashrc\n"

    # It seems that sometimes notification to master fails at startup,
    # so we do a last try at the end.
    print $file "echo '/usr/local/bin/anste-slave ready\n' > \$MOUNT/etc/rc.local\n"
}

sub _writeCopyFiles # (file)
{
    my ($self, $file) = @_;

    my $system = $self->{system};

    my $deployPath = ANSTE::Config->instance->deployPath();
    print $file "# Copy necessary files\n";
    my $commPath = '/usr/local/lib/site_perl/ANSTE/Comm/';
    my $command = $system->createMountDirCommand($commPath);
    print $file "$command\n";
    my $excPath = '/usr/local/lib/site_perl/ANSTE/Exceptions/';
    $command = $system->createMountDirCommand($excPath);
    print $file "$command\n";
    my $logPath = '/var/log/anste';
    $command  = $system->createMountDirCommand($logPath);
    print $file "$command\n";
    my $miscPath = '/var/local/anste';
    $command  = $system->createMountDirCommand($miscPath);
    print $file "$command\n";

    my %fileDest = ("$deployPath/bin/ansted" => '/usr/local/bin/',
                    "$deployPath/bin/anste-slave" => '/usr/local/bin',
                    "$deployPath/bin/anste-setup-*" => '/usr/local/bin',
                    "$deployPath/modules/ANSTE/Comm/*.pm" => $commPath,
                    "$deployPath/modules/ANSTE/Exceptions/*.pm" => $excPath,
                    "$deployPath/scripts/ansted" => '/etc/init.d/');

    foreach my $orig (keys %fileDest) {
        $command = $system->copyToMountCommand($orig, $fileDest{$orig});
        print $file "$command\n";
    }
    print $file "\n";
}

sub _writeHostsConfig # (file)
{
    my ($self, $file) = @_;

    my $system = $self->{system};
    my $host = $self->{image}->name();

    print $file "# Write host configuration\n";
    my $config = $system->hostConfig($host);
    print $file "$config\n\n";
}

1;
